#!/usr/bin/env python

import json
import visit

"""Visits ns_server metadata and emits flat metadata
   on the fast-changing time-series metrics to stdout as JSON."""

first = True

def store_conv_fast(root, parents, data, meta, coll,
                    key, val, meta_val, meta_inf, level):
    global first
    if not first:
        print ","
    first = False
    name = '-'.join(parents + [key])
    print '  "ns-%s": {' % name
    print '    "name": "%s"' % name
    if meta_inf:
        i = 0
        for k, v in meta_inf.iteritems():
            print '    ,'
            print '    "%s": "%s"' % (k, v)
            i = i + 1
    print '  }'
    root["run"]["tot_fast"] += 1

def store_conv_slow(root, parents, data, meta, coll,
                    key, val, meta_val, meta_inf, level):
    root["run"]["tot_slow"] += 1

def url_conv_before(context, path):
    return context, path

def url_conv_after(context, path, root):
    return

if __name__ == '__main__':
    print "{"
    visit.main("127.0.0.1", 8091, "/pools/default",
               {"fast": store_conv_fast,
                "slow": store_conv_slow},
               {"url_before": url_conv_before,
                "url_after": url_conv_after})
    print "}"

