LABELS = {
    "rebalance_progress": "Rebalance progress, %",
    "ops": "Ops per second",
    "cmd_get": "GET ops per second",
    "cmd_set": "SET ops per second",
    "delete_hits": "DELETE ops per second",
    "cas_hits": "CAS ops per second",
    "curr_connections": "Connections",
    "hibernated_waked": "Streaming requests wakeups per second",
    "curr_items": "Active items",
    "vb_replica_curr_items": "Replica items",
    "vb_pending_curr_items": "Pending items",
    "mem_used": "Memory used, bytes",
    "ep_meta_data_memory": "Metadata in RAM, bytes",
    "vb_active_resident_items_ratio": "Active docs resident, %",
    "vb_replica_resident_items_ratio": "Replica docs resident, %",
    "ep_num_value_ejects": "Ejections per second",
    "ep_dcp_2i_items_sent": "DCP drain rate (2i), items/second",
    "ep_dcp_2i_items_remaining": "DCP backlog (2i), items",
    "ep_dcp_replica_items_remaining": "DCP backlog (replica), items",
    "ep_dcp_replica_items_sent": "DCP drain rate (replica), items/second",
    "ep_dcp_replica_total_bytes": "DCP drain rate (replica), bytes/second",
    "ep_dcp_other_items_remaining": "DCP backlog (other), items",
    "ep_dcp_other_items_sent": "DCP drain rate (other), items/second",
    "ep_dcp_other_total_bytes": "DCP drain rate (other), bytes/second",
    "disk_write_queue": "Disk write queue, items",
    "ep_cache_miss_rate": "Cache miss ratio, %",
    "ep_bg_fetched": "Disk reads per second",
    "ep_ops_create": "Disk creates per second",
    "vb_active_ops_create": "Active Create Rate, items/sec",
    "vb_replica_ops_create": "Replica Item Create Rate, items/sec",
    "vb_pending_ops_create": "Pending Create Rate, items/sec",
    "ep_ops_update": "Disk updates per second",
    "vb_active_ops_update": "Active Update Rate, items/sec",
    "vb_replica_ops_update": "Replica Item Update Rate, items/sec",
    "vb_pending_ops_update": "Pending Update Rate, items/sec",
    "ep_diskqueue_drain": "Drain rate, items/second",
    "ep_diskqueue_fill": "Fill rate, items/second",
    "ep_queue_size": "Number of items in the queue, items",
    "avg_bg_wait_time": "BgFetcher wait time, us",
    "avg_disk_commit_time": "Disk commit time, s",
    "avg_disk_update_time": "Disk update time, us",
    "vb_avg_total_queue_age": "Average age of all items in the disk write queue, second",
    "couch_docs_data_size": "Docs data size, bytes",
    "couch_docs_actual_disk_size": "Docs total disk size, bytes",
    "couch_docs_fragmentation": "Docs fragmentation, %",
    "couch_total_disk_size": "Total disk size, bytes",
    "changes_left": "Outbound XDCR mutations, items",
    "percent_completeness": "Percentage of checked items out of all checked and to-be-replicated items",
    "docs_written": "Number of mutations that have been replicated to other clusters",
    "docs_filtered": "Number of mutations per second that have been filtered out",
    "docs_failed_cr_source": "Number of mutations that failed conflict resolution",
    "rate_replicated": "Number of replicated mutations per second",
    "bandwidth_usage": "Rate of replication, bytes/second",
    "rate_doc_opt_repd": "Number of optimistically replicated mutations per second",
    "rate_doc_checks": "Number of doc checks per second",
    "wtavg_meta_latency": "Latency of sending getMeta and waiting for conflict solution, ms",
    "wtavg_docs_latency": "Latency of sending replicated mutations to remote cluster, ms",
    "xdc_ops": "Total XDCR operations per second",
    "ep_num_ops_get_meta": "Metadata reads per second",
    "ep_num_ops_set_meta": "Metadata sets per second",
    "ep_num_ops_del_meta": "Metadata deletes per second",
    "couch_views_ops": "View reads per second",
    "couch_views_data_size": "Views data size, bytes",
    "couch_views_actual_disk_size": "Views total disk size, bytes",
    "couch_views_fragmentation": "Views fragmentation, %",
    "cpu_utilization_rate": "CPU utilization across all cores in cluster, %",
    "cpu_utilization": "CPU utilization, %",
    "swap_used": "Swap space in use across all servers in cluster, bytes",
    "beam.smp_rss": "beam.smp resident set size, bytes",
    "beam.smp_cpu": "beam.smp CPU utilization, %",
    "goxdcr_rss": "goxdcr resident set size, bytes",
    "goxdcr_cpu": "goxdcr CPU utilization, %",
    "memcached_rss": "memcached resident set size, bytes",
    "memcached_cpu": "memcached CPU utilization, %",
    "indexer_rss": "indexer resident set size, bytes",
    "indexer_cpu": "indexer CPU utilization, %",
    "projector_rss": "projector resident set size, bytes",
    "projector_cpu": "projector CPU utilization, %",
    "cbq-engine_rss": "cbq-engine resident set size, bytes",
    "cbq-engine_cpu": "cbq-engine CPU utilization, %",
    "cbft_rss": "FTS resident set size, bytes",
    "cbft_cpu": "FTS CPU utilization, %",
    "java_rss": "Java resident set size, bytes",
    "java_cpu": "Java CPU utilization, %",
    "cbc-pillowfight_rss": "cbc-pillowfight resident set size, bytes",
    "cbc-pillowfight_cpu": "cbc-pillowfight CPU utilization, %",
    "prometheus_rss": "prometheus resident set size, bytes",
    "prometheus_cpu": "prometheus CPU utilization, %",
    "memcached_sysproc_cpu_utilization": "memcached CPU utilization, %",
    "memcached_sysproc_mem_resident": "memcached resident set size, bytes",
    "prometheus_sysproc_cpu_utilization": "prometheus CPU utilization, %",
    "prometheus_sysproc_mem_resident": "prometheus resident set size, bytes",
    "cbft_sysproc_cpu_utilization": "cbft CPU utilization, %",
    "cbft_sysproc_mem_resident": "cbft resident set size, bytes",
    "eventing-produc_sysproc_cpu_utilization": "eventing-produc CPU utilization, %",
    "eventing-produc_sysproc_mem_resident": "eventing-produc resident set size, bytes",
    "indexer_sysproc_cpu_utilization": "indexer CPU utilization, %",
    "indexer_sysproc_mem_resident": "indexer resident set size, bytes",
    "ns_server_sysproc_cpu_utilization": "ns_server CPU utilization, %",
    "ns_server_sysproc_mem_resident": "ns_server resident set size, bytes",
    "cbas_sysproc_cpu_utilization": "cbas CPU utilization, %",
    "cbas_sysproc_mem_resident": "cbas resident set size, bytes",
    "cbq-engine_sysproc_cpu_utilization": "cbq-engine CPU utilization, %",
    "cbq-engine_sysproc_mem_resident": "cbq-engine resident set size, bytes",
    "goxdcr_sysproc_cpu_utilization": "goxdcr CPU utilization, %",
    "goxdcr_sysproc_mem_resident": "goxdcr resident set size, bytes",
    "java_sysproc_cpu_utilization": "Java CPU utilization, %",
    "java_sysproc_mem_resident": "Java resident set size, bytes",
    "xdcr_lag": "Total XDCR lag (from memory to memory), ms",
    "xdcr_persistence_time": "Observe latency, ms",
    "xdcr_diff": "Replication lag, ms",
    "latency_set": "SET ops latency (single mcbp request), ms",
    "latency_get": "GET ops latency (single mcbp request), ms",
    "latency_total_set": "SET ops latency including TMP error retries (overall Set() API call), ms",
    "latency_total_get": "GET ops latency including TMP error retries (overall Set() API call), ms",
    "latency_query": "Query latency, ms",
    "latency_observe": "OBSERVE latency, ms",
    "latency_persist_to": "persistTo=1 latency, ms",
    "latency_replicate_to": "replicateTo=1 latency, ms",
    "data_rps": "Disk reads/second (after merges)",
    "data_wps": "Disk writes/second (after merges)",
    "data_rbps": "Bytes/second read from the disk",
    "data_wbps": "Bytes/second written to the disk",
    "data_avgqusz": "The average queue length",
    "data_util": "Disk bandwidth utilization, %",
    "data_avg_page_cache_rr": "Average page cache resident ratio, %",
    'page_cache_hit_ratio': 'Page cache hit ratio, %',
    'page_cache_total_hits': 'Page cache total hits per second',
    "BlockCacheQuota": "Number of bytes",
    "WriteCacheQuota": "Number of bytes",
    "BlockCacheMemUsed": "Number of bytes",
    "BlockCacheHits": "Number of hits",
    "BlockCacheMisses": "Number of misses",
    "BloomFilterMemUsed": "Number of bytes",
    "BytesIncoming": "Number of bytes",
    "BytesOutgoing": "Number of bytes",
    "BytesPerRead": "Number of bytes",
    "IndexBlocksSize": "Number of bytes",
    "MemoryQuota": "Number of bytes",
    "NCommitBatches": "Number of batches",
    "NDeletes": "Number of deletes",
    "NGets": "Number of gets",
    "NInserts": "Number of inserts",
    "NReadBytes": "Number of bytes",
    "NReadBytesCompact": "Number of bytes",
    "NReadBytesGet": "Number of bytes",
    "NReadIOs": "Number of IO",
    "NReadIOsGet": "Number of IO",
    "NSets": "Number of sets",
    "NSyncs": "Number of syncs",
    "NTablesCreated": "Number of tables",
    "NTablesDeleted": "Number of tables",
    "NTableFiles": "Number of table files",
    "TableMetaMemUsed": "Memory used by table metadata",
    "TotalBloomFilterMemUsed": "Total memory used by bloomfilter",
    "NFileCountCompacts": "Number of file count compactions",
    "NWriteBytes": "Number of bytes",
    "NWriteBytesCompact": "Number of bytes",
    "NWriteIOs": "Number of IO",
    "ReadAmp": "Amplification",
    "ReadAmpGet": "Amplification",
    "ReadIOAmp": "Amplification",
    "BufferMemUsed": "Number of bytes",
    "WALMemUsed": "Number of bytes",
    "WALBufferMemUsed": "Number of bytes",
    "TreeSnapshotMemoryUsed": "Number of bytes",
    "ReadAheadBufferMemUsed": "Number of bytes",
    "TableObjectMemUsed": "Number of bytes",
    "WriteAmp": "Amplification",
    "WriteCacheMemUsed": "Number of bytes",
    "NCompacts": "Number of compactions",
    "TxnSizeEstimate": "Number of bytes",
    "NFlushes": "Number of write cache flushes performed",
    "NGetsPerSec": "Number of gets per second",
    "NSetsPerSec": "Number of sets per second",
    "NDeletesPerSec": "Number of deletes per second",
    "NCommitBatchesPerSec": "Number of commit batches per second",
    "NFlushesPerSec": "Number of flushes per second",
    "NCompactsPerSec": "Number of compacts per second",
    "NSyncsPerSec": "Number of syncs per second",
    "NReadBytesPerSec": "Number of bytes per second",
    "NReadBytesGetPerSec": "Number of bytes per second",
    "NReadBytesCompactPerSec": "Number of bytes per second",
    "BytesOutgoingPerSec": "Number of bytes per second",
    "NReadIOsPerSec": "Number of IOs per second",
    "NReadIOsGetPerSec": "Number of IOs per second",
    "BytesIncomingPerSec": "Number of bytes per second",
    "NWriteBytesPerSec": "Number of bytes per second",
    "NWriteIOsPerSec": "Number of bytes per second",
    "NWriteBytesCompactPerSec": "Number of bytes per second",
    "RecentWriteAmp": "Amplification",
    "RecentReadAmp": "Amplification",
    "RecentReadAmpGet": "Amplification",
    "RecentReadIOAmp": "Amplification",
    "RecentBytesPerRead": "Number of bytes",
    "NGetStatsPerSec": "Number of get stats per second",
    "NGetStatsComputedPerSec": "Number of get stats computed per second",
    "FlushQueueSize": "Number of tasks in the queue",
    "CompactQueueSize": "Number of tasks in the queue",
    "NBloomFilterHits": "Number of times a key didn't exist and filter correctly suggested it didn't",
    "NBloomFilterMisses": "Number of times a key didn't exist and filter incorrectly suggested it did",
    "BloomFilterFPR": "False positive ratio of the bloom filter",
    "NumNormalFlushes": "Number of normal write cache flushes",
    "NumPersistentFlushes": "Number of persistent write cache flushes",
    "NumSyncFlushes": "Number of sync write cache flushes",
    "BlockCacheHitsPerSec": "Number of hits per second",
    "BlockCacheMissesPerSec": "Number of misses per second",
    "NBloomFilterHitsPerSec": "Number of hits per second",
    "NBloomFilterMissesPerSec": "Number of misses per second",
    "RecentBlockCacheHitRatio": "Hit ratio",
    "BlockCacheHitRatio": "Hit ratio",
    "ReadIOAmpSet": "Amplification",
    "RecentReadIOAmpSet": "Amplification",
    "NReadBytesSet": "Total bytes read from disk by sets",
    "NReadIOsSet": "Number of read IOs performed by sets",
    "NReadBytesSetPerSec": "Bytes read from disk by sets per second",
    "NReadIOsSetPerSec": "Number of read IOs performed by sets per second",
    "ActiveIndexBlocksSize": "Size of all index blocks",
    "NBlocksCached": "Number of blocks in the block cache",
    "CheckpointOverheadPeriod": "Avg checkpoint overhead period without causing overflow",
    "CheckpointOverheadRatio": "Ratio of total disk usage of the LSMTrees",
    "NBlocksDropped": "Number of blocks",
    "BlockCacheBlockSize": "Block size, bytes",
    "NMemoryOptimisedCommitBatches": "Number of commit batches written in memory optimised mode",
    "TotalDiskUsage": "Uncompressed disk size of all versions of the LSM Trees",
    "HistoryDiskUsage": "Total physical size of all files part of history",
    "HistoryDataSize": "Part of the history that is not fragmented/overwritten",
    "NonResidentBloomFilterSize": "Memory reclaimed by evicting bloom filters",
    "RecentBloomFilterCacheHitRatio": "Bloom filter cache hit ratio",
    "CheckpointOverhead": "Overhead of persistent snapshots compared to actual disk usage",
    "ActiveDataSize": "Normalize logical data size based on max size on disk",
    "ActiveDiskUsage": "Uncompressed disk size of latest version of the LSM Trees",
    "CheckpointOverheadKeyIndex": "Overhead of KeyIndex",
    "CheckpointOverheadSeqIndex": "Overhead of SeqIndex",

    "ep_mem_used_primary": "Memory used, bytes",

    "mem_used_secondary": "Memory used, bytes",
    "ep_magma_total_mem_used": "Memory used, bytes",
    "ep_magma_mem_used_diff": "Memory used, bytes",

    "ep_magma_data_blocks_uncompressed_size": "Uncompressed size, bytes",
    "ep_magma_data_blocks_compressed_size": "Compressed size, bytes",
    "ep_magma_data_blocks_compression_ratio": "Compression ratio",
    "ep_magma_data_blocks_space_reduction_estimate_pct": "Estimate percent, %",

    "index_rbps": "Bytes read/second",
    "index_wbps": "Bytes written/second",
    "index_avgqusz": "The average queue length",
    "index_util": "Disk bandwidth utilization, %",
    "analytics0_rbps": "Bytes/second read from the disk",
    "analytics0_wbps": "Bytes/second written to the disk",
    "analytics0_util": "Disk bandwidth utilization, %",
    "analytics1_rbps": "Bytes/second read from the disk",
    "analytics1_wbps": "Bytes/second written to the disk",
    "analytics1_util": "Disk bandwidth utilization, %",
    "analytics2_rbps": "Bytes/second read from the disk",
    "analytics2_wbps": "Bytes/second written to the disk",
    "analytics2_util": "Disk bandwidth utilization, %",
    "analytics3_rbps": "Bytes/second read from the disk",
    "analytics3_wbps": "Bytes/second written to the disk",
    "analytics3_util": "Disk bandwidth utilization, %",
    "analytics4_rbps": "Bytes/second read from the disk",
    "analytics4_wbps": "Bytes/second written to the disk",
    "analytics4_util": "Disk bandwidth utilization, %",
    "bucket_compaction_progress": "Compaction progress, %",
    "in_bytes_per_sec": "Incoming bytes/second",
    "out_bytes_per_sec": "Outgoing bytes/second",
    "in_packets_per_sec": "Incoming packets/second",
    "out_packets_per_sec": "Outgoing packets/second",
    "ESTABLISHED": "Connections in ESTABLISHED state",
    "TIME_WAIT": "Connections in TIME_WAIT state",
    "index_num_rows_returned": "Number of rows returned by 2i",
    "num_docs_indexed": "Number of docs indexed by 2i",
    "index_scan_bytes_read": "Number of bytes per second read by a scan",
    "index_num_requests": "Number of requests served by the indexer per second",
    "index_num_docs_indexed": "Number of documents indexed by the indexer per second",
    "index_num_docs_pending": "Number of pending documents to be indexed",
    "index_num_docs_queued": "Number of queued documents to be indexed",
    "index_fragmentation": "Fragmentation of the index, %",
    "index_data_size": "Actual data size consumed by the index, bytes",
    "index_disk_size": "Total disk file size consumed by the index, bytes",
    "index_total_scan_duration": "Total time spent by 2i on scans",
    "index_items_count": "Current total indexed document count",
    "num_connections": "Number of connections to index node",
    "memory_used": "Memory used, index node, bytes",
    "memory_used_storage": "Memory used for storage, index node, bytes",
    "memory_used_queue": "Memory used for queue on index node, bytes",
    "mutation_queue_size": "Mutation queue size on index node, items",
    "num_nonalign_ts": "Number of non align ts on index node, snapshots",
    "ts_queue_size": "ts queue size on index node, snapshots",
    "avg_scan_latency": "Average scan latency, ns",
    "avg_ts_interval": "Average ts interval, ns",
    "num_completed_requests": "Number of completed requests",
    "avg_ts_items_count": "Average ts items count, items",
    "num_compactions": "Number of compactions",
    "num_rows_returned": "Number of rows returned",
    "Nth-latency": "latency, ns",
    "flush_queue_size": "Flush queue size, items",
    "avg_scan_wait_latency": "Average scan wait latency, ns",
    "disk_store_duration": "Indexer disk store duration, ms",
    "timings_storage_commit": "Average timings storage commit, ns",
    "timings_storage_del": "Average timings storage del, ns",
    "timings_storage_get": "Average timings storage get, ns",
    "timings_storage_set": "Average timings storage set, ns",
    "timings_storage_snapshot_create": "Average timings storage snapshot create, ns",
    "timings_dcp_getseqs": "Average timings dcp get seq, ns",
    "MainStore_memory_size": "Memory used by plasma",
    "MainStore_avg_throttle_dur_other": "Average timings, ns",
    "MainStore_avg_throttle_dur_reader": "Average timings, ns",
    "MainStore_avg_throttle_dur_writer": "Average timings, ns",
    "MainStore_num_cached_pages": "Number of pages cached pages by plasma",
    "MainStore_num_pages": "Total number of pages by plasma",
    "MainStore_num_pages_swapout": "Number of pages swapped out by plasma",
    "MainStore_num_pages_swapin": "Number of pages swapped in by plasma",
    "MainStore_bytes_incoming": "Incoming bytes to plasma",
    "MainStore_bytes_written": "Number of bytes written by plasma",
    "MainStore_write_amp": "Write amplification of plasma",
    "MainStore_lss_fragmentation": "lss fragmentation by plasma",
    "MainStore_cache_hits": "Number of cache hits for plasma",
    "MainStore_cache_misses": "Number of cache miss for plasma",
    "MainStore_cache_hit_ratio": "Cache hit ratio",
    "MainStore_rcache_hits": "Number of cache hits in scan path for plasma",
    "MainStore_rcache_misses": "Number of cache miss in scan path for plasma",
    "MainStore_rcache_hit_ratio": "Cache hit ratio in scan path",
    "MainStore_resident_ratio": "Indexer resident ratio for plasma, calculated by items",
    "MainStore_allocated": "Memory allocated for plasma",
    "MainStore_freed": "Memory feed by plasma",
    "MainStore_reclaimed": "Memory reclaimed by plasma",
    "MainStore_mvcc_purge_ratio": "MVCC purge ratio",
    "MainStore_memory_quota": "Indexer Memory quota, Bytes",
    "MainStore_reclaim_pending": "Memory reclaim pending by plasma",
    "MainStore_lss_blk_read_bs": "lss_blk_read_bs, Bytes",
    "MainStore_lss_blk_gc_reads_bs": "lss_blk_gc_reads_bs, Bytes",
    "MainStore_lss_blk_rdr_reads_bs": "lss_blk_rdr_reads_bs, Bytes",
    "MainStore_rlss_num_reads": "rlss_num_reads, Bytes",
    "MainStore_compressed_percent": "Compressed page, %",
    "MainStore_compressed_compressible_percent": "Compressible page, %",
    "MainStore_compress_cache_hit_ratio": "Compress hit ratio",
    "MainStore_rcompress_cache_hit_ratio": "RCompress_cache hit ratio",
    "MainStore_lss_cached_pages_percent": "lss_cached_pages, %",
    "MainStore_num_burst_visits": "Burst Visits",
    "MainStore_num_periodic_visits": "Periodic Visits",
    "MainStore_inserts": "Number of inserts",
    "MainStore_burst_eviction_rate": "pages/second",
    "MainStore_periodic_eviction_rate": "pages/second",
    "MainStore_eviction_rate_reader": "pages/second",
    "MainStore_eviction_rate_writer": "pages/second",
    "MainStore_eviction_rate_swapper": "pages/second",
    "MainStore_eviction_rate_other": "pages/second",
    "BackStore_memory_size": "Memory used by plasma",
    "BackStore_avg_throttle_dur_other": "Average timings, ns",
    "BackStore_avg_throttle_dur_reader": "Average timings, ns",
    "BackStore_avg_throttle_dur_writer": "Average timings, ns",
    "BackStore_num_cached_pages": "Number of pages cached pages by plasma",
    "BackStore_num_pages": "Total number of pages by plasma",
    "BackStore_num_pages_swapout": "Number of pages swapped out by plasma",
    "BackStore_num_pages_swapin": "Number of pages swapped in by plasma",
    "BackStore_bytes_incoming": "Incoming bytes to plasma",
    "BackStore_bytes_written": "Number of bytes written by plasma",
    "BackStore_write_amp": "Write amplification of plasma",
    "BackStore_lss_fragmentation": "lss fragmentation by plasma",
    "BackStore_cache_hits": "Number of cache hits for plasma",
    "BackStore_cache_misses": "Number of cache miss for plasma",
    "BackStore_cache_hit_ratio": "Cache hit ratio",
    "BackStore_rcache_hits": "Number of cache hits in scan path for plasma",
    "BackStore_rcache_misses": "Number of cache miss in scan path for plasma",
    "BackStore_rcache_hit_ratio": "Cache hit ratio in scan path",
    "BackStore_resident_ratio": "Indexer resident ratio for plasma, calculated by items",
    "BackStore_allocated": "Memory allocated for plasma",
    "BackStore_freed": "Memory feed by plasma",
    "BackStore_reclaimed": "Memory reclaimed by plasma",
    "BackStore_lss_blk_read_bs": "lss_blk_read_bs, Bytes",
    "BackStore_lss_blk_gc_reads_bs": "lss_blk_gc_reads_bs, Bytes",
    "BackStore_lss_blk_rdr_reads_bs": "lss_blk_rdr_reads_bs, Bytes",
    "BackStore_rlss_num_reads": "rlss_num_reads, Bytes",
    "BackStore_reclaim_pending": "Memory reclaim pending by plasma",
    "BackStore_mvcc_purge_ratio": "MVCC purge ratio",
    "BackStore_compressed_percent": "Compressed page, %",
    "BackStore_compressed_compressible_percent": "Compressible page, %",
    "BackStore_compress_cache_hit_ratio": "Compress hit ratio",
    "BackStore_rcompress_cache_hit_ratio": "RCompress_cache hit ratio",
    "BackStore_lss_cached_pages_percent": "lss_cached_pages, %",
    "BackStore_num_burst_visits": "Burst Visits",
    "BackStore_num_periodic_visits": "Periodic Visits",
    "BackStore_inserts": "Number of inserts",
    "BackStore_burst_eviction_rate": "pages/second",
    "BackStore_periodic_eviction_rate": "pages/second",
    "BackStore_eviction_rate_reader": "pages/second",
    "BackStore_eviction_rate_writer": "pages/second",
    "BackStore_eviction_rate_swapper": "pages/second",
    "BackStore_eviction_rate_other": "pages/second",
    "mm_allocated": "Memory allocated, Indexer, bytes",
    "mm_resident": "Memory resident, Indexer, Bytes",
    "mm_metadata": "Memory metadata, Indexer, Bytes",
    "mm_allocated_js": "Memory allocated, Indexer, bytes",
    "mm_resident_js": "Memory resident, Indexer, Bytes",
    "mm_metadata_js": "Memory metadata, Indexer, Bytes",
    "bin_10240_FragPercent": "Fragmentation %",
    "bin_10240_Resident": "Memory resident, Bytes",
    "bin_1024_FragPercent": "Fragmentation %",
    "bin_1024_Resident": "Memory resident, Bytes",
    "bin_112_FragPercent": "Fragmentation %",
    "bin_112_Resident": "Memory resident, Bytes",
    "bin_12288_FragPercent": "Fragmentation %",
    "bin_12288_Resident": "Memory resident, Bytes",
    "bin_1280_FragPercent": "Fragmentation %",
    "bin_1280_Resident": "Memory resident, Bytes",
    "bin_128_FragPercent": "Fragmentation %",
    "bin_128_Resident": "Memory resident, Bytes",
    "bin_14336_FragPercent": "Fragmentation %",
    "bin_14336_Resident": "Memory resident, Bytes",
    "bin_1536_FragPercent": "Fragmentation %",
    "bin_1536_Resident": "Memory resident, Bytes",
    "bin_160_FragPercent": "Fragmentation %",
    "bin_160_Resident": "Memory resident, Bytes",
    "bin_16_FragPercent": "Fragmentation %",
    "bin_16_Resident": "Memory resident, Bytes",
    "bin_1792_FragPercent": "Fragmentation %",
    "bin_1792_Resident": "Memory resident, Bytes",
    "bin_192_FragPercent": "Fragmentation %",
    "bin_192_Resident": "Memory resident, Bytes",
    "bin_2048_FragPercent": "Fragmentation %",
    "bin_2048_Resident": "Memory resident, Bytes",
    "bin_224_FragPercent": "Fragmentation %",
    "bin_224_Resident": "Memory resident, Bytes",
    "bin_2560_FragPercent": "Fragmentation %",
    "bin_2560_Resident": "Memory resident, Bytes",
    "bin_256_FragPercent": "Fragmentation %",
    "bin_256_Resident": "Memory resident, Bytes",
    "bin_3072_FragPercent": "Fragmentation %",
    "bin_3072_Resident": "Memory resident, Bytes",
    "bin_320_FragPercent": "Fragmentation %",
    "bin_320_Resident": "Memory resident, Bytes",
    "bin_32_FragPercent": "Fragmentation %",
    "bin_32_Resident": "Memory resident, Bytes",
    "bin_3584_FragPercent": "Fragmentation %",
    "bin_3584_Resident": "Memory resident, Bytes",
    "bin_384_FragPercent": "Fragmentation %",
    "bin_384_Resident": "Memory resident, Bytes",
    "bin_4096_FragPercent": "Fragmentation %",
    "bin_4096_Resident": "Memory resident, Bytes",
    "bin_448_FragPercent": "Fragmentation %",
    "bin_448_Resident": "Memory resident, Bytes",
    "bin_48_FragPercent": "Fragmentation %",
    "bin_48_Resident": "Memory resident, Bytes",
    "bin_5120_FragPercent": "Fragmentation %",
    "bin_5120_Resident": "Memory resident, Bytes",
    "bin_512_FragPercent": "Fragmentation %",
    "bin_512_Resident": "Memory resident, Bytes",
    "bin_6144_FragPercent": "Fragmentation %",
    "bin_6144_Resident": "Memory resident, Bytes",
    "bin_640_FragPercent": "Fragmentation %",
    "bin_640_Resident": "Memory resident, Bytes",
    "bin_64_FragPercent": "Fragmentation %",
    "bin_64_Resident": "Memory resident, Bytes",
    "bin_7168_FragPercent": "Fragmentation %",
    "bin_7168_Resident": "Memory resident, Bytes",
    "bin_768_FragPercent": "Fragmentation %",
    "bin_768_Resident": "Memory resident, Bytes",
    "bin_80_FragPercent": "Fragmentation %",
    "bin_80_Resident": "Memory resident, Bytes",
    "bin_8192_FragPercent": "Fragmentation %",
    "bin_8192_Resident": "Memory resident, Bytes",
    "bin_896_FragPercent": "Fragmentation %",
    "bin_896_Resident": "Memory resident, Bytes",
    "bin_8_FragPercent": "Fragmentation %",
    "bin_8_Resident": "Memory resident, Bytes",
    "bin_96_FragPercent": "Fragmentation %",
    "bin_96_Resident": "Memory resident, Bytes",
    "query_requests": "Number of N1QL requests processed per second",
    "query_selects": "Number of N1QL selects processed per second",
    "query_avg_req_time": "Average end-to-end time to process a query, seconds",
    "query_avg_svc_time": "Average time to execute a query, seconds",
    "query_avg_response_size": "Average size of the data returned by a query, Bytes",
    "query_avg_result_count": "Average number of results (documents) returned by a query",
    "query_errors": "Number of N1QL errors returned per second",
    "query_warnings": "Number of N1QL errors returned per second",
    "query_requests_250ms": "Number of queries that take longer than 250ms per second",
    "query_requests_500ms": "Number of queries that take longer than 500ms per second",
    "query_requests_1000ms": "Number of queries that take longer than 1000ms per second",
    "query_requests_5000ms": "Number of queries that take longer than 5000ms per second",
    "query_invalid_requests": "Number of requests for unsupported endpoints per second",
    "cbft_num_bytes_used_disk": "FTS index size on disk in GB",
    "cbft_doc_count": "FTS indexing rate",
    "cbft_num_bytes_used_ram": "FTS ram used by cbft process",
    "cbft_pct_cpu_gc": "FTS garbage collection CPU usage",
    "cbft_query_slow": "FTS slow query",
    "cbft_query_timeout": "FTS timeout query",
    "cbft_query_error": "FTS error query",
    "cbft_batch_merge_count": "FTS batch merge_count",
    "cbft_total_gc": "FTS garbage collector count",
    "cbft_num_bytes_live_data": "FTS live data size",
    "cbft_total_term_searchers": "FTS total term search",
    "cbft_query_total": "FTS total queries",
    "cbft_total_bytes_query_results": "FTS total query bytes",
    "cbft_writer_execute_batch_count": "FTS writer batch count",
    "cbft_latency_get": "FTS latency in ms",
    "cbft_avg_queries_latency": "FTS average queries latency (server)",
    "cbft_query_throughput": "FTS average queries per second",
    "elastic_latency_get": "ElasticSearch latency in ms",
    "cbft_total_bytes_indexed": "FTS total index size",
    "cbft_num_recs_to_persist": "FTS number of records in queue",
    "cbft_num_root_memorysegments": "FTS number of memory segments at root",
    "cbft_num_root_filesegments": "FTS number of disk segments at root",
    "elastic_cache_hit": "Elasticsearch query cache hit",
    "elastic_cache_size": "Elasticsearch query cache size",
    "elastic_filter_cache_size": "Elasticsearch filter cache size",
    "elastic_active_search": "Elasticsearch active search",
    "elastic_query_total": "Elasticsearch total query",
    "jts_throughput": "JTS Throughput, queries/second",
    "jts_latency": "JTS Latency, ms",
    "indexer_pread": "indexer pread system calls/second",
    "indexer_pwrite": "indexer pwrite system calls/second",
    "memcached_pread": "memcached pread system calls/second",
    "memcached_pwrite": "memcached pwrite system calls/second",
    'MemFree': 'The amount of physical memorynot used by the system, bytes',
    'Dirty': 'Memory waiting to be written back to disk, bytes',
    'Buffers': 'Memory in buffer cache, bytes',
    'Cached': 'Memory in the pagecache, bytes',
    'SUnreclaim': 'Memory cannot be reclaimed, bytes',
    'data_bytes_read': 'Total bytes read from the disk',
    'data_bytes_written': 'Total bytes written to the disk',
    "DCP_MUTATION": "DCP mutations processed by function",
    "DOC_TIMER_EVENTS": "DOC timer events processed by function",
    "CRON_TIMER_EVENTS": "CRON timer events processed by function",
    "eventing-produc_rss": "eventing-producer resident set size, bytes",
    "eventing-produc_cpu": "eventing-producer CPU utilization, %",
    "ep_tmp_oom_errors": "Number of back-offs sent per second due to OOM",
    "eventing_consumer_cpu": "Eventing consumer CPU utilization, %",
    "eventing_consumer_rss": "Eventing consumer rss used, Bytes",
    "on_update_success": "OnUpdate() Successful events",
    "DcpEventsRemaining": "DCP events remaining",
    "heap_used": "JVM heap used, bytes",
    "gc_count": "GC count",
    "gc_time": "GC time, ms",
    "io_reads": "IO reads, bytes",
    "io_writes": "IO writes, bytes",
    "system_load_average": "Average load",
    "disk_used": "Total disk used in bytes",
    "thread_count": "Number of threads in use",
    "allocstall": "direct reclaim calls",
    "syncgateway__global__resource_utilization__process_cpu_percent_utilization": "process_cpu_percent_utilization",
    "syncgateway__global__resource_utilization__go_memstats_heapinuse": "go_memstats_heapinuse",
    "syncgateway__per_db__db__database__doc_writes_bytes_blip": "doc_writes_bytes_blip",
    "syncgateway__per_db__db__database__doc_reads_bytes_blip": "doc_reads_bytes_blip",
    "syncgateway__per_db__db__delta_sync__delta_cache_hit": "delta_cache_hit",
    "syncgateway__per_db__db__delta_sync__delta_cache_miss": "delta_cache_miss",
    "syncgateway__per_db__db__cache__rev_cache_hits": "rev_cache_hits",
    "syncgateway__per_db__db__cache__rev_cache_misses": "rev_cache_misses",
    "syncgateway__global__resource_utilization__system_memory_total": "system memory total",
    "syncgateway__global__resource_utilization__admin_net_bytes_sent": "admin_net_bytes_sent",
    "syncgateway__global__resource_utilization__admin_net_bytes_recv": "admin_net_bytes_recv",
    "syncgateway__global__resource_utilization__go_memstats_sys": "go_memstats_sys",
    "syncgateway__global__resource_utilization__go_memstats_heapalloc": "go_memstats_heapalloc",
    "syncgateway__global__resource_utilization__go_memstats_heapidle": "go_memstats_heapidle",
    "syncgateway__global__resource_utilization__go_memstats_heapreleased": "go_memstats_heapreleased",
    "syncgateway__global__resource_utilization__go_memstats_pausetotalns": "go_memstats_pausetotalns",
    "syncgateway__global__resource_utilization__go_memstats_stackinuse": "go_memstats_stackinuse",
    "syncgateway__global__resource_utilization__goroutines_high_watermark": "goroutines_high_watermark",
    "syncgateway__global__resource_utilization__num_goroutines": "num_goroutines",
    "syncgateway__global__resource_utilization__process_memory_resident": "process_memory_resident",
    "syncgateway__global__resource_utilization__pub_net_bytes_recv": "pub_net_bytes_recv",
    "syncgateway__global__resource_utilization__pub_net_bytes_sent": "pub_net_bytes_sent",
    "syncgateway__global__resource_utilization__go_memstats_stacksys": "go_memstats_stacksys",
    "syncgateway__global__resource_utilization__error_count": "error_count",
    "syncgateway__global__resource_utilization__warn_count": "warn_count",
    "syncgateway__per_db__db__cache__rev_cache_bypass": "rev_cache_bypass",
    "syncgateway__per_db__db__cache__chan_cache_hits": "chan_cache_hits",
    "syncgateway__per_db__db__cache__chan_cache_misses": "chan_cache_misses",
    "syncgateway__per_db__db__cache__chan_cache_active_revs": "chan_cache_active_revs",
    "syncgateway__per_db__db__cache__chan_cache_tombstone_revs": "chan_cache_tombstone_revs",
    "syncgateway__per_db__db__cache__chan_cache_removal_revs": "chan_cache_removal_revs",
    "syncgateway__per_db__db__cache__chan_cache_num_channels": "chan_cache_num_channels",
    "syncgateway__per_db__db__cache__chan_cache_max_entries": "chan_cache_max_entries",
    "syncgateway__per_db__db__cache__chan_cache_pending_queries": "chan_cache_pending_queries",
    "syncgateway__per_db__db__cache__chan_cache_channels_added": "chan_cache_channels_added",
    "syncgateway__per_db__db__cache__chan_cache_channels_evicted_inactive": "chan_cache_channels_evicted_inactive",
    "syncgateway__per_db__db__cache__chan_cache_channels_evicted_nru": "chan_cache_channels_evicted_nru",
    "syncgateway__per_db__db__cache__chan_cache_compact_count": "chan_cache_compact_count",
    "syncgateway__per_db__db__cache__chan_cache_compact_time": "chan_cache_compact_time",
    "syncgateway__per_db__db__cache__num_active_channels": "num_active_channels",
    "syncgateway__per_db__db__cache__num_skipped_seqs": "num_skipped_seqs",
    "syncgateway__per_db__db__cbl_replication_pull__attachment_pull_bytes": "attachment_pull_bytes",
    "syncgateway__per_db__db__cbl_replication_pull__attachment_pull_count": "attachment_pull_count",
    "syncgateway__per_db__db__cbl_replication_pull__request_changes_count": "request_changes_count",
    "syncgateway__per_db__db__cbl_replication_pull__request_changes_time": "request_changes_time",
    "syncgateway__per_db__db__cbl_replication_pull__rev_processing_time": "rev_processing_time",
    "syncgateway__per_db__db__cbl_replication_pull__rev_send_count": "rev_send_count",
    "syncgateway__per_db__db__cbl_replication_pull__rev_send_latency": "rev_send_latency",
    "syncgateway__per_db__db__cbl_replication_push__attachment_push_bytes": "attachment_push_bytes",
    "syncgateway__per_db__db__cbl_replication_push__attachment_push_count": "attachment_push_count",
    "syncgateway__per_db__db__cbl_replication_push__doc_push_count": "doc_push_count",
    "syncgateway__per_db__db__cbl_replication_push__propose_change_count": "propose_change_count",
    "syncgateway__per_db__db__cbl_replication_push__propose_change_time": "propose_change_time",
    "syncgateway__per_db__db__cbl_replication_push__sync_function_count": "sync_function_count",
    "syncgateway__per_db__db__cbl_replication_push__sync_function_time": "sync_function_time",
    "syncgateway__per_db__db__cbl_replication_push__write_processing_time": "write_processing_time",
    "syncgateway__per_db__db__database__doc_writes_bytes": "doc_writes_bytes",
    "syncgateway__per_db__db__database__num_doc_reads_blip": "num_doc_reads_blip",
    "syncgateway__per_db__db__database__num_doc_reads_rest": "num_doc_reads_rest",
    "syncgateway__per_db__db__database__num_doc_writes": "num_doc_writes",
    "syncgateway__per_db__db__cache__abandoned_seqs": "abandoned_seqs",
    "syncgateway__per_db__db__cache__high_seq_cached": "high_seq_cached",
    "syncgateway__per_db__db__cache__high_seq_stable": "high_seq_stable",
    "syncgateway__per_db__db__cache__skipped_seq_len": "skipped_seq_len",
    "syncgateway__per_db__db__cache__pending_seq_len": "pending_seq_len",
    "syncgateway__per_db__db__database__sequence_get_count": "sequence_get_count",
    "syncgateway__per_db__db__database__sequence_incr_count": "sequence_incr_count",
    "syncgateway__per_db__db__database__sequence_reserved_count": "sequence_reserved_count",
    "syncgateway__per_db__db__database__sequence_assigned_count": "sequence_assigned_count",
    "syncgateway__per_db__db__database__sequence_released_count": "sequence_released_count",
    "syncgateway__per_db__db__database__crc32c_match_count": "crc32c_match_count",
    "syncgateway__per_db__db__database__num_replications_active": "num_replications_active",
    "syncgateway__per_db__db__database__num_replications_total": "num_replications_total",
    "syncgateway__per_db__db__delta_sync__delta_pull_replication_count": "delta_pull_replication_count",
    "syncgateway__per_db__db__delta_sync__delta_push_doc_count": "delta_push_doc_count",
    "syncgateway__per_db__db__database__num_tombstones_compacted": "num_tombstones_compacted",
    "syncgateway__per_db__db__database__doc_writes_xattr_bytes": "doc_writes_xattr_bytes",
    "syncgateway__per_db__db__database__warn_xattr_size_count": "warn_xattr_size_count",
    "syncgateway__per_db__db__database__warn_channels_per_doc_count": "warn_channels_per_doc_count",
    "syncgateway__per_db__db__database__warn_grants_per_doc_count": "warn_grants_per_doc_count",
    "syncgateway__per_db__db__database__dcp_received_count": "dcp_received_count",
    "syncgateway__per_db__db__database__high_seq_feed": "high_seq_feed",
    "syncgateway__per_db__db__database__dcp_received_time": "dcp_received_time",
    "syncgateway__per_db__db__database__dcp_caching_count": "dcp_caching_count",
    "syncgateway__per_db__db__database__dcp_caching_time": "dcp_caching_time",
    "syncgateway__per_db__db__delta_sync__deltas_requested": "deltas_requested",
    "syncgateway__per_db__db__delta_sync__deltas_sent": "deltas_sent",
    "syncgateway__per_db__db__shared_bucket_import__import_count": "import_count",
    "syncgateway__per_db__db__shared_bucket_import__import_cancel_cas": "import_cancel_cas",
    "syncgateway__per_db__db__shared_bucket_import__import_error_count": "error_count",
    "syncgateway__per_db__db__shared_bucket_import__import_processing_time": "import_processing_time",
    "syncgateway__per_db__db__cbl_replication_push__conflict_write_count": "conflict_write_count",
    "syncgateway__per_db__db__cbl_replication_pull__num_pull_repl_active_one_shot": "num_pull_repl_active_one_shot",
    "syncgateway__per_db__db__cbl_replication_pull__num_pull_repl_active_continuous": "num_pull_repl_active_continuous",
    "syncgateway__per_db__db__cbl_replication_pull__num_pull_repl_total_one_shot": "num_pull_repl_total_one_shot",
    "syncgateway__per_db__db__cbl_replication_pull__num_pull_repl_total_continuous": "num_pull_repl_total_continuous",
    "syncgateway__per_db__db__cbl_replication_pull__num_pull_repl_since_zero": "num_pull_repl_since_zero",
    "syncgateway__per_db__db__cbl_replication_pull__num_pull_repl_caught_up": "num_pull_repl_caught_up",
    "syncgateway__per_db__db__cbl_replication_pull__max_pending": "pull__max_pending",
    "syncgateway__per_db__db__security__num_docs_rejected": "num_docs_rejected",
    "syncgateway__per_db__db__security__num_access_errors": "num_access_errors",
    "syncgateway__per_db__db__security__auth_success_count": "auth_success_count",
    "syncgateway__per_db__db__security__auth_failed_count": "auth_failed_count",
    "syncgateway__per_db__db__security__total_auth_time": "total_auth_time",
    "syncGateway_import__import_count": "import_count",
    "sgimport_latency": "sgimport_latency",
    "syncgateway__per_db__db__gsi_views__access_count": "gsi_views__access_count",
    "syncgateway__per_db__db__gsi_views__roleAccess_count": "gsi_views__roleAccess_count",
    "syncgateway__per_db__db__gsi_views__channels_count": "gsi_views__channels_count",
    "sgw_resource_utilization_process_cpu_percent_utilization": "process_cpu_percent_utilization",
    "sgw_resource_utilization_process_memory_resident": "process_memory_resident",
    "sgw_resource_utilization_system_memory_total": "system memory total",
    "sgw_resource_utilization_pub_net_bytes_sent": "pub_net_bytes_sent",
    "sgw_resource_utilization_pub_net_bytes_recv": "pub_net_bytes_recv",
    "sgw_resource_utilization_admin_net_bytes_sent": "admin_net_bytes_sent",
    "sgw_resource_utilization_admin_net_bytes_recv": "admin_net_bytes_recv",
    "sgw_resource_utilization_num_goroutines": "num_goroutines",
    "sgw_resource_utilization_goroutines_high_watermark": "goroutines_high_watermark",
    "sgw_resource_utilization_go_memstats_sys": "go_memstats_sys",
    "sgw_resource_utilization_go_memstats_heapalloc": "go_memstats_heapalloc",
    "sgw_resource_utilization_go_memstats_heapidle": "go_memstats_heapidle",
    "sgw_resource_utilization_go_memstats_heapinuse": "go_memstats_heapinuse",
    "sgw_resource_utilization_go_memstats_heapreleased": "go_memstats_heapreleased",
    "sgw_resource_utilization_go_memstats_stackinuse": "go_memstats_stackinuse",
    "sgw_resource_utilization_go_memstats_stacksys": "go_memstats_stacksys",
    "sgw_resource_utilization_go_memstats_pausetotalns": "go_memstats_pausetotalns",
    "sgw_resource_utilization_error_count": "error_count",
    "sgw_resource_utilization_warn_count": "warn_count",
    "sgw_cache_rev_cache_hits": "rev_cache_hits",
    "sgw_cache_rev_cache_misses": "rev_cache_misses",
    "sgw_cache_rev_cache_bypass": "rev_cache_bypass",
    "sgw_cache_chan_cache_hits": "chan_cache_hits",
    "sgw_cache_chan_cache_misses": "chan_cache_misses",
    "sgw_cache_chan_cache_active_revs": "chan_cache_active_revs",
    "sgw_cache_chan_cache_tombstone_revs": "chan_cache_tombstone_revs",
    "sgw_cache_chan_cache_removal_revs": "chan_cache_removal_revs",
    "sgw_cache_chan_cache_num_channels": "chan_cache_num_channels",
    "sgw_cache_chan_cache_max_entries": "chan_cache_max_entries",
    "sgw_cache_chan_cache_pending_queries": "chan_cache_pending_queries",
    "sgw_cache_chan_cache_channels_added": "chan_cache_channels_added",
    "sgw_cache_chan_cache_channels_evicted_inactive": "chan_cache_channels_evicted_inactive",
    "sgw_cache_chan_cache_channels_evicted_nru": "chan_cache_channels_evicted_nru",
    "sgw_cache_chan_cache_compact_count": "chan_cache_compact_count",
    "sgw_cache_chan_cache_compact_time": "chan_cache_compact_time",
    "sgw_cache_num_active_channels": "num_active_channels",
    "sgw_cache_num_skipped_seqs": "num_skipped_seqs",
    "sgw_cache_abandoned_seqs": "abandoned_seqs",
    "sgw_cache_high_seq_cached": "high_seq_cached",
    "sgw_cache_high_seq_stable": "high_seq_stable",
    "sgw_cache_skipped_seq_len": "skipped_seq_len",
    "sgw_cache_pending_seq_len": "pending_seq_len",
    "sgw_database_sequence_get_count": "sequence_get_count",
    "sgw_database_sequence_incr_count": "sequence_incr_count",
    "sgw_database_sequence_reserved_count": "sequence_reserved_count",
    "sgw_database_sequence_assigned_count": "sequence_assigned_count",
    "sgw_database_sequence_released_count": "sequence_released_count",
    "sgw_database_crc32c_match_count": "crc32c_match_count",
    "sgw_database_num_replications_active": "num_replications_active",
    "sgw_database_num_replications_total": "num_replications_total",
    "sgw_database_num_doc_writes": "num_doc_writes",
    "sgw_database_num_tombstones_compacted": "num_tombstones_compacted",
    "sgw_database_doc_writes_bytes": "doc_writes_bytes",
    "sgw_database_doc_writes_xattr_bytes": "doc_writes_xattr_bytes",
    "sgw_database_num_doc_reads_rest": "num_doc_reads_rest",
    "sgw_database_num_doc_reads_blip": "num_doc_reads_blip",
    "sgw_database_doc_writes_bytes_blip": "doc_writes_bytes_blip",
    "sgw_database_doc_reads_bytes_blip": "doc_reads_bytes_blip",
    "sgw_database_warn_xattr_size_count": "warn_xattr_size_count",
    "sgw_database_warn_channels_per_doc_count": "warn_channels_per_doc_count",
    "sgw_database_dcp_received_count": "dcp_received_count",
    "sgw_database_high_seq_feed": "high_seq_feed",
    "sgw_database_dcp_received_time": "dcp_received_time",
    "sgw_database_dcp_caching_count": "dcp_caching_count",
    "sgw_database_dcp_caching_time": "dcp_caching_time",
    "sgw_database_conflict_write_count": "conflict_write_count",
    "sgw_shared_bucket_import_import_count": "import_count",
    "sgw_shared_bucket_import_import_cancel_cas": "import_cancel_cas",
    "sgw_shared_bucket_import_import_error_count": "error_count",
    "sgw_shared_bucket_import_import_processing_time": "import_processing_time",
    "sgw_replication_push_doc_push_count": "doc_push_count",
    "sgw_replication_push_write_processing_time": "write_processing_time",
    "sgw_database_sync_function_time": "sync_function_time",
    "sgw_database_sync_function_count": "sync_function_count",
    "sgw_replication_push_propose_change_time": "propose_change_time",
    "sgw_replication_push_propose_change_count": "propose_change_count",
    "sgw_replication_push_attachment_push_count": "attachment_push_count",
    "sgw_replication_push_attachment_push_bytes": "attachment_push_bytes",
    "sgw_replication_pull_num_pull_repl_active_one_shot": "num_pull_repl_active_one_shot",
    "sgw_replication_pull_num_pull_repl_active_continuous": "num_pull_repl_active_continuous",
    "sgw_replication_pull_num_pull_repl_total_one_shot": "num_pull_repl_total_one_shot",
    "sgw_replication_pull_num_pull_repl_total_continuous": "num_pull_repl_total_continuous",
    "sgw_replication_pull_num_pull_repl_since_zero": "num_pull_repl_since_zero",
    "sgw_replication_pull_num_pull_repl_caught_up": "num_pull_repl_caught_up",
    "sgw_replication_pull_request_changes_count": "request_changes_count",
    "sgw_replication_pull_request_changes_time": "request_changes_time",
    "sgw_replication_pull_rev_send_count": "rev_send_count",
    "sgw_replication_pull_rev_send_latency": "rev_send_latency",
    "sgw_replication_pull_rev_processing_time": "rev_processing_time",
    "sgw_replication_pull_max_pending": "pull_max_pending",
    "sgw_replication_pull_attachment_pull_count": "attachment_pull_count",
    "sgw_replication_pull_attachment_pull_bytes": "attachment_pull_bytes",
    "sgw_security_num_docs_rejected": "num_docs_rejected",
    "sgw_security_num_access_errors": "num_access_errors",
    "sgw_security_auth_success_count": "auth_success_count",
    "sgw_security_auth_failed_count": "auth_failed_count",
    "sgw_security_total_auth_time": "total_auth_time",
    "sgw_gsi_views_access_count": "gsi_views_access_count",
    "sgw_gsi_views_roleAccess_count": "gsi_views_roleAccess_count",
    "sgw_gsi_views_channels_count": "gsi_views_channels_count",
    "kv_meter_ru_total": "Read Units per sec",
    "kv_meter_wu_total": "Write Units per sec",
    "kv_meter_cu_total": "Compute Units per sec",
    "index_meter_ru_total": "Read Units per sec",
    "index_meter_wu_total": "Write Units per sec",
    "n1ql_meter_cu_total": "Compute Units per sec",
    "fts_meter_ru_total": "Read Units per sec",
    "fts_meter_wu_total": "Write Units per sec",
    "total_read_ops_rejected": "Total read ops (queries) rejected ",
    "total_write_ops_rejected": "Total write ops capped",
    "total_write_throttle_seconds": "Total seconds of write throttling",
    "total_batch_rejection_backoff_time_ms":"Total ms spent in exponential backoff",
    "total_batch_limting_timeouts": "Total batch executions timed out in exponential backoff (during batch execution rejects",
    "total_read_ops_capped": "Total read ops (queries) capped (because of their huge RUs)",
    "utilization:cpuPercent": "Utilisation Cpu Percentage by FTS ",
    "utilization:memoryBytes": "Utilisation Memory Percentage by FTS",
    "kv_ep_total_enqueued_rate": "Mutations enqueued per sec in checkpoints",
    "kv_ep_total_deduplicated_rate": "Mutations deduplicated per sec in checkpoints",
    "kv_ep_total_deduplicated_flusher_rate": "Mutations deduplicated per sec in flushers"
}

HISTOGRAMS = (
    "latency_get",
    "latency_set",
    "latency_total_get",
    "latency_total_set",
    "latency_query",
    "latency_observe",
    "latency_persist_to",
    "latency_replicate_to",
    "xdcr_lag",
    "xdcr_persistence_time",
    "xdcr_diff",
    "replication_meta_latency_wt",
    "replication_docs_latency_wt",
    "avg_bg_wait_time",
    "avg_disk_commit_time",
    "avg_disk_update_time",
    "vb_avg_total_queue_age",
    "query_avg_req_time",
    "query_avg_svc_time",
    "cbft_latency_get",
    "elastic_latency_get",
    "Nth-latency",
    "sgimport_latency",
    "jts_latency",
)

ZOOM_HISTOGRAMS = (
    "latency_get",
    "latency_set",
    "latency_total_get",
    "latency_total_set",
    "latency_query",
    "avg_bg_wait_time",
    "cbft_latency_get",
    "elastic_latency_get",
    "Nth-latency",
)

NON_ZERO_VALUES = (
    "rebalance_progress",
    "bucket_compaction_progress",

    "ops",
    "cmd_get",
    "cmd_set",
    "delete_hits",
    "cas_hits",

    "couch_views_ops",
    "couch_views_data_size",
    "couch_views_actual_disk_size",
    "couch_views_fragmentation",
    "couch_docs_fragmentation",

    "hibernated_waked",

    "ep_dcp_2i_items_sent",
    "ep_dcp_2i_items_remaining",
    "ep_dcp_replica_items_remaining",
    "ep_dcp_replica_items_sent",
    "ep_dcp_replica_total_bytes",
    "ep_dcp_other_items_remaining",
    "ep_dcp_other_items_sent",
    "ep_dcp_other_total_bytes",

    "ep_tmp_oom_errors",
    "disk_write_queue",
    "ep_diskqueue_drain",
    "ep_diskqueue_fill",
    "ep_queue_size",
    "ep_cache_miss_rate",
    "ep_num_value_ejects",
    "ep_bg_fetched",
    "ep_ops_create",
    "vb_active_ops_create",
    "vb_replica_ops_create",
    "vb_pending_ops_create",
    "ep_ops_update",
    "vb_active_ops_update",
    "vb_replica_ops_update",
    "vb_pending_ops_update",
    "avg_bg_wait_time",
    "avg_disk_commit_time",
    "avg_disk_update_time",
    "vb_replica_curr_items",
    "vb_pending_curr_items",
    "vb_avg_total_queue_age",

    "BlockCacheQuota",
    "WriteCacheQuota",
    "BlockCacheMemUsed",
    "BlockCacheHits",
    "BlockCacheMisses",
    "BloomFilterMemUsed",
    "BytesIncoming",
    "BytesOutgoing",
    "BytesPerRead",
    "IndexBlocksSize",
    "MemoryQuota",
    "NCommitBatches",
    "NDeletes",
    "NGets",
    "NInserts",
    "NReadBytes",
    "NReadBytesCompact",
    "NReadBytesGet",
    "NReadIOs",
    "NReadIOsGet",
    "NSets",
    "NSyncs",
    "NTablesCreated",
    "NTablesDeleted",
    "NTableFiles",
    "TableMetaMemUsed",
    "NFileCountCompacts",
    "TotalBloomFilterMemUsed",
    "NWriteBytes",
    "NWriteBytesCompact",
    "NWriteIOs",
    "ReadAmp",
    "ReadAmpGet",
    "ReadIOAmp",
    "BufferMemUsed",
    "WALMemUsed",
    "WALBufferMemUsed",
    "TreeSnapshotMemoryUsed",
    "ReadAheadBufferMemUsed",
    "TableObjectMemUsed",
    "WriteAmp",
    "WriteCacheMemUsed",
    "NCompacts",
    "TxnSizeEstimate",
    "NFlushes",
    "NGetsPerSec",
    "NSetsPerSec",
    "NDeletesPerSec",
    "NCommitBatchesPerSec",
    "NFlushesPerSec",
    "NCompactsPerSec",
    "NSyncsPerSec",
    "NReadBytesPerSec",
    "NReadBytesGetPerSec",
    "NReadBytesCompactPerSec",
    "BytesOutgoingPerSec",
    "NReadIOsPerSec",
    "NReadIOsGetPerSec",
    "BytesIncomingPerSec",
    "NWriteBytesPerSec",
    "NWriteIOsPerSec",
    "NWriteBytesCompactPerSec",
    "RecentWriteAmp",
    "RecentReadAmp",
    "RecentReadAmpGet",
    "RecentReadIOAmp",
    "RecentBytesPerRead",
    "NGetStatsPerSec",
    "NGetStatsComputedPerSec",
    "FlushQueueSize",
    "CompactQueueSize",
    "NBloomFilterHits",
    "NBloomFilterMisses",
    "BloomFilterFPR",
    "NumNormalFlushes",
    "NumPersistentFlushes",
    "NumSyncFlushes",
    "BlockCacheHitsPerSec",
    "BlockCacheMissesPerSec",
    "NBloomFilterHitsPerSec",
    "NBloomFilterMissesPerSec",
    "RecentBlockCacheHitRatio",
    "BlockCacheHitRatio",
    "ReadIOAmpSet",
    "RecentReadIOAmpSet",
    "NReadBytesSet",
    "NReadIOsSet",
    "NReadBytesSetPerSec",
    "NReadIOsSetPerSec",
    "ActiveIndexBlocksSize",
    "NBlocksCached",
    "CheckpointOverheadPeriod",
    "CheckpointOverheadRatio",
    "NBlocksDropped",
    "BlockCacheBlockSize",
    "NMemoryOptimisedCommitBatches",
    "TotalDiskUsage",
    "HistoryDiskUsage",
    "HistoryDataSize",
    "NonResidentBloomFilterSize",
    "RecentBloomFilterCacheHitRatio",
    "CheckpointOverhead",
    "ActiveDataSize",
    "ActiveDiskUsage",
    "CheckpointOverheadKeyIndex",
    "CheckpointOverheadSeqIndex",

    "ep_mem_used_primary",

    "mem_used_secondary",
    "ep_magma_total_mem_used",
    "ep_magma_mem_used_diff",

    "ep_magma_data_blocks_uncompressed_size",
    "ep_magma_data_blocks_compressed_size",
    "ep_magma_data_blocks_compression_ratio",
    "ep_magma_data_blocks_space_reduction_estimate_pct",

    "xdc_ops",
    "ep_num_ops_get_meta",
    "ep_num_ops_set_meta",
    "ep_num_ops_del_meta",
    "docs_failed_cr_source",
    "docs_filtered",
    "docs_failed_cr_source",
    "rate_doc_opt_repd",
    "rate_doc_checks",

    "replication_changes_left",
    "replication_size_rep_queue",
    "replication_rate_replication",
    "replication_bandwidth_usage",
    "replication_work_time",
    "replication_commit_time",
    "replication_active_vbreps",
    "replication_waiting_vbreps",
    "replication_num_checkpoints",
    "replication_num_failedckpts",
    "replication_meta_latency_wt",
    "replication_docs_latency_wt",

    "query_errors",
    "query_warnings",
    "query_requests_250ms",
    "query_requests_500ms",
    "query_requests_1000ms",
    "query_requests_5000ms",
    "query_invalid_requests",

    "index_fragmentation",
    "index_items_count",
    "index_num_docs_indexed",
    "index_num_docs_pending",
    "index_num_docs_queued",
    "index_num_requests",
    "index_num_rows_returned",
    "num_docs_indexed"
    "index_scan_bytes_read",
    "index_data_size",
    "index_disk_size",
    "index_total_scan_duration",

    "MainStore_memory_size",
    "MainStore_num_cached_pages",
    "MainStore_num_pages",
    "MainStore_num_pages_swapout",
    "MainStore_num_pages_swapin",
    "MainStore_bytes_incoming",
    "MainStore_bytes_written",
    "MainStore_write_amp",
    "MainStore_lss_fragmentation",
    "MainStore_cache_hits",
    "MainStore_cache_misses",
    "MainStore_cache_hit_ratio",
    "MainStore_rcache_hits",
    "MainStore_rcache_misses",
    "MainStore_rcache_hit_ratio",
    "MainStore_resident_ratio",
    "MainStore_allocated",
    "MainStore_freed",
    "MainStore_reclaimed",
    "MainStore_reclaim_pending",
    "MainStore_mvcc_purge_ratio",
    "MainStore_memory_quota",
    "MainStore_compressed_percent",
    "MainStore_compressed_compressible_percent",
    "MainStore_compress_cache_hit_ratio",
    "MainStore_rcompress_cache_hit_ratio",
    "MainStore_lss_cached_pages_percent",
    "MainStore_num_burst_visits",
    "MainStore_num_periodic_visits",

    "BackStore_memory_size",
    "BackStore_num_cached_pages",
    "BackStore_num_pages",
    "BackStore_num_pages_swapout",
    "BackStore_num_pages_swapin",
    "BackStore_bytes_incoming",
    "BackStore_bytes_written",
    "BackStore_write_amp",
    "BackStore_lss_fragmentation",
    "BackStore_cache_hits",
    "BackStore_cache_misses",
    "BackStore_cache_hit_ratio",
    "BackStore_rcache_hits",
    "BackStore_rcache_misses",
    "BackStore_rcache_hit_ratio",
    "BackStore_resident_ratio",
    "BackStore_allocated",
    "BackStore_freed",
    "BackStore_reclaimed",
    "BackStore_reclaim_pending",
    "BackStore_mvcc_purge_ratio",
    "BackStore_compressed_percent",
    "BackStore_compressed_compressible_percent",
    "BackStore_compress_cache_hit_ratio",
    "BackStore_rcompress_cache_hit_ratio",
    "BackStore_lss_cached_pages_percent",
    "BackStore_num_burst_visits",
    "BackStore_num_periodic_visits",

    "DCP_MUTATION",
    "DOC_TIMER_EVENTS",
    "CRON_TIMER_EVENTS",

    "swap_used",

    "data_rps",
    "data_wps",
    "data_rbps",
    "data_wbps",
    "data_avgqusz",
    "data_util",
    "index_rbps",
    "index_wbps",
    "index_avgqusz",
    "index_util",

    "TIME_WAIT",

    "syncGateway_rest__requests_0000ms",
    "syncGateway_rest__requests_0100ms",
    "syncGateway_rest__requests_0200ms",
    "syncGateway_rest__requests_0300ms",
    "syncGateway_rest__requests_0700ms",
    "syncGateway_rest__requests_0800ms",
    "syncGateway_rest__requests_0900ms",
    "syncGateway_rest__requests_1000ms",
    "syncGateway_stats__bulkApi.BulkDocsRollingMean",
    "syncGateway_stats__bulkApi.BulkGetPerDocRollingMean",
    "syncGateway_stats__bulkApi.BulkGetRollingMean",
    "syncGateway_stats__bulkApi_BulkDocsPerDocRollingMean",
    "syncGateway_stats__indexReader.getChanges.Count",
    "syncGateway_stats__indexReader.getChanges.Time",
    "syncGateway_stats__indexReader.getChanges.UseCached",
    "syncGateway_stats__indexReader.getChanges.UseIndexed",
    "syncGateway_stats__indexReader.numReaders.OneShot",
    "syncGateway_stats__indexReader.numReaders.Persistent",
    "syncGateway_stats__indexReader.pollPrincipals.Count",
    "syncGateway_stats__indexReader.pollPrincipals.Time:",
    "syncGateway_stats__indexReader.pollReaders.Count",
    "syncGateway_stats__indexReader.pollReaders.Time",
    "syncGateway_stats__indexReader.seqHasher.GetClockTime",
    "syncGateway_stats__indexReader.seqHasher.GetHash",
)

PALETTE = (
    "#51A351",
    "#f89406",
    "#7D1935",
    "#4A96AD",
    "#DE1B1B",
    "#E9E581",
    "#A2AB58",
    "#FFE658",
    "#118C4E",
    "#193D4F",
)
