#!/usr/bin/env python

from server import Server
from mc_source import MemcachedSource
from json_handler import JsonHandler

if __name__ == "__main__":

    server = Server(ip="10.3.121.217")
    mc_src = MemcachedSource(server, "default")
    mc_src.connect()
    mc_stats = mc_src.feed()
    hanlder = JsonHandler("cbstats.json")
    hanlder.handle(mc_stats)
    mc_src.disconnect()