LABELS = {
    "rebalance_progress": "Rebalance progress, %",
    "ops": "Ops per sec",
    "cmd_get": "GET ops per sec",
    "cmd_set": "SET ops per sec",
    "delete_hits": "DELETE ops per sec",
    "cas_hits": "CAS ops per sec",
    "curr_connections": "Connections",
    "curr_items": "Active items",
    "mem_used": "Memory used, bytes",
    "ep_meta_data_memory": "Metadata in RAM, bytes",
    "vb_active_resident_items_ratio": "Cctive docs resident, %",
    "vb_replica_resident_items_ratio": "Replica docs resident, %",
    "ep_num_value_ejects": "Ejections per sec",
    "disk_write_queue": "Disk write queue, items",
    "ep_cache_miss_rate": "Cache miss ratio, %",
    "ep_bg_fetched": "Disk reads per sec",
    "ep_diskqueue_drain": "Drain rate, items/sec",
    "avg_bg_wait_time": "BgFetcher wait time, sec",
    "avg_disk_commit_time": "Disk commit time, sec",
    "avg_disk_update_time": "Disk update time, sec",
    "couch_docs_data_size": "Docs data size, bytes",
    "couch_docs_actual_disk_size": "Docs total disk size, bytes",
    "couch_docs_fragmentation": "Docs fragmentation, %",
    "couch_total_disk_size": "Total disk size, bytes",
    "replication_changes_left": "Outbound XDCR mutations, items",
    "replication_size_rep_queue": "XDC replication queue, bytes",
    "replication_rate_replication": "Mutation replication rate per sec",
    "replication_bandwidth_usage": "Data replication rate, bytes/sec",
    "replication_work_time": "Secs in replicating",
    "replication_commit_time": "Secs in checkpointin",
    "replication_active_vbreps": "Active vbucket replications",
    "replication_waiting_vbreps": "Waiting vbucket replications",
    "replication_num_checkpoints": "Checkpoints issued",
    "replication_num_failedckpts": "Checkpoints failed",
    "replication_meta_latency_wt": "Weighted meta ops latency, ms",
    "replication_docs_latency_wt": "Weighted doc ops latency, ms",
    "xdc_ops": "Total XDCR operations per sec",
    "ep_num_ops_get_meta": "Metadata reads per sec",
    "ep_num_ops_set_meta": "Metadata sets per sec",
    "ep_num_ops_del_meta": "Metadata deletes per sec",
    "couch_views_ops": "View reads per sec",
    "couch_views_data_size": "Views data size, bytes",
    "couch_views_actual_disk_size": "Views total disk size, bytes",
    "couch_views_fragmentation": "Views fragmentation, %",
    "beam.smp_rss": "beam.smp resident set size, bytes",
    "beam.smp_cpu": "beam.smp CPU utilization, %",
    "memcached_cpu": "memcached CPU utilization, %",
    "xdcr_lag": "Total XDCR lag (from memory to memory), ms",
    "xdcr_persistence_time": "Observe latency, ms",
    "xdcr_diff": "Replication lag, ms",
    "latency_set": "SET ops latency, ms",
    "latency_get": "GET ops latency, ms",
    "latency_query": "Query latency, ms",
    "Sys": "Bytes obtained from system",
    "Alloc": "Bytes allocated and still in use",
    "HeapAlloc": "Bytes allocated and still in use",
    "HeapObjects": "Total number of allocated objects",
    "PauseTotalNs": "Total GC pause time, ns",
    "PauseNs": "GC pause time, ns",
    "NumGC": "GC events",
}
